/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 model.gltf --transform 
Files: model.gltf [81.12MB] > C:\Users\emull\Projects\react-three-vite\model-transformed.glb [6.84MB] (92%)
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={266.27} near={51.139} fov={25.115} position={[-41.767, 146.74, 46.413]} rotation={[Math.PI / 2, -0.685, -0.433]} />
      <mesh geometry={nodes['Pipe_Types_Carbon_Steel_-_Welded,_STD_1643407'].geometry} material={nodes['Pipe_Types_Carbon_Steel_-_Welded,_STD_1643407'].material} />
    </group>
  )
}

useGLTF.preload('/model-transformed.glb')
